### ISSUE TITLE
Volume button crashes all games

### ISSUE THREAD

**Issue by JasonB32** [OtherCrashOverride/prosystem-odroid-go#1] opened 2018-08-04 00:09 UTC
Not really a big deal, but when you press the volume button it glitch/vibrates the game like it was repeating it's last sound really fast then if you press volume again it crashes the game going back to the menu. I notice there's no sound meter in the menu system if it's not the Go-Play main menu. So I just go flash back to the Go-Play menu, adjust the volume, then flash back to Pro-System Atari and I set it that way.

I'm just so appreciative that you made this emulator for it, thank you @OtherCrashOverride

**Comment by kamotswind** [comment] 2018-08-04 02:38
Can confirm this bug.

**Comment by OtherCrashOverride** [comment] 2018-08-04 04:31
This bug exists in the 2600 and 7800 emulators.  Sometimes Volume works correctly, other times it crashes.  The cause is currently unknown.

**Comment by JasonB32** [comment] 2018-08-04 04:38
Oh ok fair enough. It's not a huge deal, I can always adjust sound before going into the emulator. Morely just letting you know.

Thank you @OtherCrashOverride

**Comment by OtherCrashOverride** [comment] 2018-08-06 07:16
Resolved by 5bfd4113b0e03de86b78ab4e771f7d5f88891d1f

**Closed as completed by OtherCrashOverride** 2018-08-06 07:16 UTC
